### ISSUE TITLE
Scraping author and publisher as well

### ISSUE THREAD

**Issue by dersuchendee** [Addono/worldcat-scraper#4]
Hi, when scraping author and publisher I get the correct output but it doesn't save it in the output file. Why?

The code:
```
 def parse(self, response):
        for title in response.css('.name a > strong ::text').extract():
            yield {"title:": title}
        for author in response.css('.author ::text').extract():
            yield {"author:": author}
        for publisher in response.css('.publisher span ::text').extract():
            yield {"publisher:": publisher}
```

**Comment by Addono** [comment]
Every time you call `yield` it will write a row. What I'm guessing is that Scrapy only creates the columns for the first result it sees, then ignoring all unknown columns.

Instead, you should yield an dictionary with all columns:
https://docs.scrapy.org/en/latest/intro/tutorial.html#extracting-data-in-our-spider

Anyway, it should be added as a feature now, give it a go :)
